export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'I like to read. I believe “A reader lives a thousand lives before he dies . . . The man who never reads lives only one.”',
    headline: 'About Me',
    description: 'My name is Jumana jambughodawala. I am a B.tech student at MSU Vadodara Computer Sciene And Engineering Department. I was born and raised in Dahod, Gujarat.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/jumana.jpg'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transitions without getting charged any fees. ',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/jumana.jpg'),
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
}
